{% set name = "lb-nightly-functions" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-functions-{{ version }}.tar.gz
  sha256: 2e1acabbfc319de2c320aa5055c6c86c1a06ba394af5fe37ee8db3be19ec6239

build:
  number: 0
  noarch: python
  entry_points:
    - lb-wrapcmd = lb.nightly.functions.common:lb_wrapcmd
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - aiohttp >=3.7.4,<4.0.0
    - archspec >=0.1.2,<0.2.0
    - gitpython >=3.1.18,<4.0.0
    - lb-nightly-configuration >=0.2,<0.3
    - lb-nightly-db >=0.1,<0.2
    - lb-nightly-utils >=0.3,<0.4
    - lbplatformutils >=4.3.8,<5.0.0
    - opensearch-py >=1.0.0,<2.0.0
    - python >=3.6,<4.0
    - python-gitlab >=2.9.0,<3.0.0
    - spython >=0.1.14,<0.2.0

test:
  imports:
    - lb
    - lb.nightly.functions
  commands:
    - pip check
    - lb-wrapcmd --help
  requires:
    - git
    - pip

about:
  home: https://pypi.org/project/lb-nightly-functions/
  summary: Core functions for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maszyman
